# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, choices=[('yellow', 'Yellow'), ('red', 'Red'), ('grey', 'Grey')], max_length=255, null=True)),
                ('size', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
